### ISSUE TITLE
Unable to edit contact number in facility update

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#252] opened 2020-04-14 18:50 UTC
I am unable to change the `Emergency Contact Number` for a facility in facility update page

**Comment by SandeepThomas** [comment] 2020-04-15 03:46
@bodhish could you please check again? Im not able to reproduce this in staging.

**Comment by SandeepThomas** [comment] 2020-04-18 14:25
Closing as not reproducible.

**Closed as completed by SandeepThomas** 2020-04-18 14:25 UTC
Labels: bug
