### ISSUE TITLE
SOS feature for Resources

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1018] opened 2021-05-03 15:26 UTC
There must be a feature in CARE oxygen module for facilities to file urgent demand for oxygen.

There must be a log of such requests.

The district admin must have an option to mark these as resolved. 

A log of all such requests must be available to the district administrator.

(This is a feature available in COVID JAGRATHA, hence the request from the field)

**Comment by aparnacoronasafe** [comment] 2021-05-04 11:33
Had a discussion with the field level staff again today:

What we require is a Kanban Board for resolving these SOS, as the shifting module.

The Kanban board must have the following list:

**Request**: All requests from the facilities must appear in this list. The district team will see this and Approve/Reject the request. The reasons of rejecting the request must be noted down and must be visible to the facility. Distirct team will also mention if police escort is required for transportation. 

**Rejected request**- all rejected requests must land here.

**Approved Requests**- This list must have all approved requests within the district. This list must be editable by the staff of the "Department of industries". They are responsible to locate available oxygen. Once a supplier is identified, The card is moved to the next list "To transport"

**To transport**- this list is editable by the RTO and visible to the police (only for the requests tagged as needing escort by the district team). The RTO will arrange for transportation.  Once the transportation is arranged, The card is moved to the next list

**Escort to be arranged**- once RTO arranges transportation, only for requests needing escort, the police must arrange for escort and move the card to the next list.

**Transportation in progress**- all oxygen that is being transported appears here. Once the destination receives it, the card is moved by the destination facility to the next list.

**Completed**- all completed request comes here.


- [ ] Create SOS Oxygen request form (available to facilities)- this form should have the following fields:-
< details to be filled in by Aparna>

- [ ] Create new user types: Dept. of industries, RTO, police

**Comment by aparnacoronasafe** [comment] 2021-05-06 16:30
@bodhish can you guide me on how to execute this using google sheets or any efficient but easy method?

**Comment by bodhish** [comment] 2021-05-13 07:20
@aparnacoronasafe need more insight on the statues

**Comment by vigneshhari** [comment] 2021-05-17 08:31
Duplicate of #1105

**Closed as completed by vigneshhari** 2021-05-17 08:31 UTC
Labels: urgent, Backend, Frontend
