### ISSUE TITLE
when the telemedicine for a patient is disabled, the doctor assignment persists

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1198] opened 2021-05-24 20:58 UTC
When telemedicine for a patient i enabled and doc is assigned, even after the telemedicine is turned off, the doc assignment continues. 

This may lead to the doctor getting flooded with patient assignment since the facilities will keep assigning patients while no one unassigns.

**Comment by vigneshhari** [comment] 2021-05-26 02:44
Unless the patient has created a new consultation the doctor will still have access to the patient, this is by design and not a flaw. The assigned doctor was not just designed for telemedicine but for physical facilities as well, what you require is a telemedicine filter in the patients, that the telemedicine doctors can apply in the patient's list page.
Kindly close this issue and create another one as this issue won't be worked on.

**Comment by bodhish** [comment] 2021-06-14 05:28
closing in favor of https://github.com/coronasafe/care_fe/issues/1398

**Closed as completed by bodhish** 2021-06-14 05:28 UTC
