### ISSUE TITLE
doctors for tele medicine log in type.

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#767] opened 2020-10-04 08:51 UTC
this must be a pool of doctors who could sign in and they could be assigned to any Covid management center as an when needed, so that we could properly use the doctors as needed.

these doctors would be sitting at home, hence they could be assigned to any Covid management center irrespective of where they are staying or loging in from

**Comment by vigneshhari** [comment] 2020-10-07 15:05
There is already a user type called doctors and we already have a way to assign users to a facility , there is no API Pending

**Comment by vigneshhari** [comment] 2020-10-08 10:23
Duplicate of #788, Close either one of the issue

**Comment by athulmanuel** [comment] 2020-10-10 19:19
@vigneshhari the basic concept is that we will have a pool of doctors who might be assigned to different facilities at a same time. So we either a new type called 'tele medicine doctor' which can be assigned to either each patient or a facility. This assigning must be done either self or by moderator

**Comment by bodhish** [comment] 2020-10-17 11:20
@athulmanuel I have created an option to assign doctors to a consultation. 

The list will display all doctors in the district ordered by last_scene. 
Let's try using this.

**Comment by amruthavijay88** [comment] 2020-10-19 06:49
Tested - it works, verified.

**Closed as completed** 2020-10-24 21:59 UTC
Labels: needs review
