### ISSUE TITLE
External result: upload limit

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1790] opened 2021-09-04 07:20 UTC
currently external result upload accepts only lists with upto 100 entries. 

Please expand this list to atleast 1000 entries.

**Comment by arpancodes** [comment] 2021-09-05 09:15
@aparnacoronasafe I don't think there's any limit. Please check again? I was able to upload 873 records at once...

**Comment by Apurva-Nagar** [comment] 2021-09-05 13:39
@arpancodes Vignesh is working on it, he told that we aren't imposing any limits but this issue is being caused by the database slowing down.

**Comment by arpancodes** [comment] 2022-05-18 10:13
@aparnacoronasafe @gigincg closing this issue.

**Closed as completed by arpancodes** 2022-05-18 10:13 UTC
