### ISSUE TITLE
Resources : comments

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1266] opened 2021-05-29 13:53 UTC
All comments in resources appear on each resource request. 

Only the relevant comments may be noted visible there

**Comment by vigneshhari** [comment] 2021-05-29 14:34
Fixed in the backend , @aparnacoronasafe why wasn't this noted during testing?

**Comment by bodhish** [comment] 2021-06-14 05:21
Looks like the issue is now fixed

**Closed as completed by bodhish** 2021-06-14 05:21 UTC
