### ISSUE TITLE
The filtering logic is not working

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#1387] opened 2021-06-12 08:13 UTC
Filter by event type in notifications is not working. 

https://www.loom.com/share/0ca4e620d7704188ab5e079360111ce2

**Comment by arpancodes** [comment] 2021-06-18 12:30
@vigneshhari the caused by object is empty for 'SHIFTING_UPDATE'

**Comment by vigneshhari** [comment] 2021-06-18 13:18
@arpancodes the frontend should not crash if the object is empty, this should be handled since there will be notifications with caused objects empty.

**Comment by arpancodes** [comment] 2021-06-18 14:13
@vigneshhari it isn't crashing it's just that I am not able to redirect to the shifting update page due to the empty object...

**Comment by vigneshhari** [comment] 2021-06-18 14:15
how is the shifting issue related to this issue then? The Backend has this bug resolved all new shifting updates should have this data now.

**Comment by arpancodes** [comment] 2021-06-18 14:26
In the PR @aparnacoronasafe commented and marked as `test failed` that's why I asked

**Closed as completed** 2021-06-18 20:54 UTC
Labels: bug, Backend
